name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Install dependencies
      run: npm install


    - name: Run Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: CRITICAL,HIGH


    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v6
      with:
         context: .
         push: true
         
         tags: | 
           ${{ vars.DOCKERHUB_USER }}/abdullah-shop:${{ github.ref_name }}
           ${{ vars.DOCKERHUB_USER }}/abdullah-shop:latest
           ${{ vars.DOCKERHUB_USER }}/abdullah-shop:${{ github.sha }}

    - name: Deploy to EC2
    
      uses: actions/checkout@v4
     
     
    - name: SSH to prod server & create app folder 
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
       
          script: |
            echo "Starting deployement & package install"
            sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER && newgrp docker 
            mkdir -p devops

    - name: Copy docker compose files via SSH
      uses: appleboy/scp-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          
          source: docker-compose.prod.yml
          target: ~/devops    

    - name: SSH to prod server & run the app 
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          
          script: |
            echo "running app"
          
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}

            export DOCKER_TAG=${{ github.sha }}
            echo ${{secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
            cd ~/devops
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --pull always